FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# Expose to 0.0.0.0 so we can access the dev server outside the container
CMD ["npm", "run", "dev", "--", "--host"]
